/**
 * @file    line_array_9ch.c
 * @brief   9-Channel Analog IR Sensor Array Driver — STM32 HAL Implementation
 *
 * Supersedes: line_array.c (8-channel digital TCRT5000 driver on PA0–PA7)
 *
 * Dependencies (generated by STM32CubeMX):
 *   - ADC1 in Scan + Continuous + DMA Circular mode, 9 channels, 12-bit,
 *     480-cycle sampling, EOC at end of sequence
 *   - DMA1 Stream0 Ch0, Peripheral→Memory, Circular, Word (32-bit) width
 *   - stm32f4xx_hal_adc.h
 *   - stm32f4xx_hal_flash_ex.h  (for Flash erase/program)
 *
 * DMA buffer layout (LA_OVERSAMPLE_N = 16 scan passes, LA_NUM_SENSORS = 9):
 *   Scan pass 0: [S1_0, S2_0, S3_0, S4_0, S5_0, S6_0, S7_0, S8_0, S9_0]
 *   Scan pass 1: [S1_1, S2_1, ...]
 *   ...
 *   Scan pass 15: [S1_15, S2_15, ... S9_15]
 *   Total = 9 × 16 = 144 uint32_t values
 *
 * Build target: STM32F401RCT6, STM32CubeIDE, C11, -O2
 */

#include "line_array_9ch.h"
#include <string.h>
#include <math.h>
#include <stdio.h>

/* ─── DMA Buffer ───────────────────────────────────────────────────────────── */
/*  Declared volatile because DMA writes it asynchronously.
 *  We take a snapshot in LA_Update() before processing.                        */
static volatile uint32_t _dma_buf[LA_DMA_BUFFER_SIZE];

/* ─── Internal State ───────────────────────────────────────────────────────── */
static ADC_HandleTypeDef *_hadc           = NULL;
static LA_Calibration_t   _cal;
static LA_Result_t        _last_result;
static float              _ema[LA_NUM_SENSORS];
static bool               _ema_init[LA_NUM_SENSORS];
static int                _junction_consec = 0;
static uint32_t           _lost_cycles     = 0;
static bool               _initialised     = false;

/* Snapshot buffer — non-volatile copy of _dma_buf taken at start of LA_Update */
static uint32_t _snap[LA_DMA_BUFFER_SIZE];

/* ─── Private Helpers ──────────────────────────────────────────────────────── */

/**
 * @brief  Average LA_OVERSAMPLE_N DMA snapshot values for one sensor.
 *         DMA layout: _snap[pass * LA_NUM_SENSORS + sensor_idx]
 */
static uint16_t prv_oversample(int sensor_idx) {
    uint32_t sum = 0;
    for (int pass = 0; pass < LA_OVERSAMPLE_N; pass++) {
        sum += _snap[pass * LA_NUM_SENSORS + sensor_idx];
    }
    return (uint16_t)(sum / LA_OVERSAMPLE_N);
}

/**
 * @brief  Apply EMA filter with spike rejection to one sensor.
 * @param  idx  Sensor index (0–8)
 * @param  raw  New oversampled ADC reading
 * @return Filtered ADC value as float
 */
static float prv_apply_ema(int idx, uint16_t raw) {
    float fraw = (float)raw;

    if (!_ema_init[idx]) {
        _ema[idx]      = fraw;
        _ema_init[idx] = true;
        return fraw;
    }

    /* Spike rejection: if ADC changed by more than LA_SPIKE_THRESHOLD in one
     * sample, it is almost certainly electrical noise — discard and keep prev. */
    if (fabsf(fraw - _ema[idx]) > (float)LA_SPIKE_THRESHOLD) {
        fraw = _ema[idx];  /* Reject spike */
    }

    /* EMA: filtered[n] = alpha * raw[n] + (1 - alpha) * filtered[n-1] */
    _ema[idx] = LA_EMA_ALPHA * fraw + (1.0f - LA_EMA_ALPHA) * _ema[idx];
    return _ema[idx];
}

/**
 * @brief  Normalise a filtered ADC value using per-sensor calibration.
 * @return 0.0 = white surface (on line), 1.0 = black surface (off line)
 */
static float prv_normalise(int idx, float filtered) {
    float range = (float)(_cal.max_val[idx] - _cal.min_val[idx]);
    if (range < 10.0f) range = 10.0f;  /* Safety: avoid divide-by-zero */
    float norm = (filtered - (float)_cal.min_val[idx]) / range;
    if (norm < 0.0f) norm = 0.0f;
    if (norm > 1.0f) norm = 1.0f;
    return norm;
}

/**
 * @brief  Set default calibration values (used when Flash is uninitialized).
 */
static void prv_set_default_cal(void) {
    for (int i = 0; i < LA_NUM_SENSORS; i++) {
        _cal.min_val[i] = LA_CAL_DEFAULT_MIN;
        _cal.max_val[i] = LA_CAL_DEFAULT_MAX;
    }
    _cal.magic    = 0x00000000UL;
    _cal.is_valid = false;
}

/**
 * @brief  Load calibration struct from internal Flash.
 * @return true if magic word matches and data is valid
 */
static bool prv_load_cal_from_flash(void) {
    const LA_Calibration_t *flash_cal =
        (const LA_Calibration_t *)LA_CAL_FLASH_ADDR;

    if (flash_cal->magic != LA_CAL_MAGIC) {
        return false;  /* Not yet calibrated or Flash erased */
    }

    memcpy(&_cal, flash_cal, sizeof(LA_Calibration_t));
    _cal.is_valid = true;
    return true;
}

/**
 * @brief  Erase the calibration Flash sector and write current _cal struct.
 *
 * IMPORTANT: This erases the entire Flash sector containing LA_CAL_FLASH_ADDR.
 *            Ensure no other data is stored in that sector.
 *            For STM32F401 with 1 MB Flash, sector 7 starts at 0x0807F800.
 *            Adjust LA_CAL_FLASH_SECTOR / LA_CAL_FLASH_ADDR for other variants.
 *
 * @return HAL_OK on success, HAL error code on failure
 */
static HAL_StatusTypeDef prv_save_cal_to_flash(void) {
    HAL_StatusTypeDef status;

    /* Unlock Flash for programming */
    status = HAL_FLASH_Unlock();
    if (status != HAL_OK) return status;

    /* Erase target sector */
    FLASH_EraseInitTypeDef erase_cfg = {
        .TypeErase    = FLASH_TYPEERASE_SECTORS,
        .VoltageRange = FLASH_VOLTAGE_RANGE_3,   /* 2.7 V – 3.6 V supply */
        .Sector       = LA_CAL_FLASH_SECTOR,
        .NbSectors    = 1,
    };
    uint32_t sector_error = 0xFFFFFFFFUL;
    status = HAL_FLASHEx_Erase(&erase_cfg, &sector_error);
    if (status != HAL_OK || sector_error != 0xFFFFFFFFUL) {
        HAL_FLASH_Lock();
        return (status != HAL_OK) ? status : HAL_ERROR;
    }

    /* Write calibration struct word by word */
    _cal.magic    = LA_CAL_MAGIC;
    _cal.is_valid = true;

    const uint32_t *src  = (const uint32_t *)(void *)&_cal;
    uint32_t        addr = LA_CAL_FLASH_ADDR;
    size_t          nwords = (sizeof(LA_Calibration_t) + 3) / 4;

    for (size_t i = 0; i < nwords; i++) {
        status = HAL_FLASH_Program(FLASH_TYPEPROGRAM_WORD, addr, src[i]);
        if (status != HAL_OK) {
            HAL_FLASH_Lock();
            return status;
        }
        addr += 4;
    }

    HAL_FLASH_Lock();
    return HAL_OK;
}

/* ─── Public API Implementation ────────────────────────────────────────────── */

void LA_Init(ADC_HandleTypeDef *hadc) {
    if (_initialised) return;

    _hadc = hadc;

    /* Start ADC1 with DMA in circular mode.
     * DMA fills _dma_buf continuously; we snapshot it each LA_Update() call. */
    HAL_ADC_Start_DMA(_hadc, (uint32_t *)_dma_buf, LA_DMA_BUFFER_SIZE);

    /* Initialise EMA state */
    memset(_ema,      0, sizeof(_ema));
    memset(_ema_init, 0, sizeof(_ema_init));

    /* Load calibration from Flash; use defaults if not found */
    if (!prv_load_cal_from_flash()) {
        prv_set_default_cal();
        /* Operator should run LA_Calibrate() before competition! */
    }

    /* Initialise result struct */
    memset(&_last_result, 0, sizeof(_last_result));
    _last_result.centroid = LA_CENTRE_INDEX;
    _last_result.error    = 0.0f;
    _junction_consec      = 0;
    _lost_cycles          = 0;

    _initialised = true;
}

void LA_Calibrate(bool white_surface) {
    if (!_initialised) return;

    /* Collect 32 averaged readings for stable calibration */
    const int CAL_ROUNDS = 32;
    uint32_t  acc[LA_NUM_SENSORS] = {0};

    for (int round = 0; round < CAL_ROUNDS; round++) {
        /* Allow DMA to fill a fresh set of samples */
        HAL_Delay(5);  /* 5 ms — 16 scan passes at 480-cycle ADC = < 1 ms */

        /* Snapshot DMA buffer and oversample */
        memcpy(_snap, (const void *)_dma_buf, sizeof(_snap));
        for (int i = 0; i < LA_NUM_SENSORS; i++) {
            acc[i] += prv_oversample(i);
        }
    }

    for (int i = 0; i < LA_NUM_SENSORS; i++) {
        uint16_t avg = (uint16_t)(acc[i] / CAL_ROUNDS);
        if (white_surface) {
            _cal.min_val[i] = avg;
        } else {
            _cal.max_val[i] = avg;
        }
    }

    /* After BLACK step: validate and persist to Flash */
    if (!white_surface) {
        bool valid = true;
        for (int i = 0; i < LA_NUM_SENSORS; i++) {
            if (_cal.max_val[i] < (uint16_t)(_cal.min_val[i] + 200)) {
                valid = false;  /* Black ≤ white + 200 — sensor not working */
            }
        }
        if (valid) {
            prv_save_cal_to_flash();
            _cal.is_valid = true;
        }
        /* If invalid, operator must fix mounting height / circuit and retry */
    }
}

void LA_Update(LA_Result_t *result) {
    if (!_initialised || !result) return;

    /* ── Step 1: Atomic snapshot of DMA buffer ───────────────────────────── */
    /* Disable DMA interrupt briefly to avoid mid-fill snapshot — OR simply
     * copy quickly (9×16 uint32 = 576 bytes, ~0.1 µs on STM32F401 @ 84 MHz).
     * At 100 Hz the DMA refill period >> copy time, so race condition risk is
     * negligible. For absolute safety, use DMA half-transfer callback instead. */
    memcpy(_snap, (const void *)_dma_buf, sizeof(_snap));

    LA_Result_t r;
    memset(&r, 0, sizeof(r));

    /* ── Step 2: Oversample — average 16 DMA values per sensor ──────────── */
    for (int i = 0; i < LA_NUM_SENSORS; i++) {
        r.adc_raw[i] = prv_oversample(i);
    }

    /* ── Step 3: EMA filter + spike rejection ────────────────────────────── */
    /* ── Step 4: Normalise [0=white, 1=black] ────────────────────────────── */
    /* ── Step 5: Invert to line_val [1=on line, 0=off line] ─────────────── */
    for (int i = 0; i < LA_NUM_SENSORS; i++) {
        float filtered = prv_apply_ema(i, r.adc_raw[i]);
        r.raw_norm[i]  = prv_normalise(i, filtered);
        r.line_val[i]  = 1.0f - r.raw_norm[i];  /* White (on line) = 1.0 */
    }

    /* ── Step 6: Count active sensors ────────────────────────────────────── */
    r.active_count = 0;
    for (int i = 0; i < LA_NUM_SENSORS; i++) {
        if (r.line_val[i] > LA_ACTIVE_THRESHOLD) r.active_count++;
    }

    /* ── Step 7: Weighted centroid ───────────────────────────────────────── */
    float sum_pos = 0.0f, sum_wt = 0.0f;
    for (int i = 0; i < LA_NUM_SENSORS; i++) {
        if (r.line_val[i] > LA_CONTRIB_THRESHOLD) {
            sum_pos += (float)i * r.line_val[i];
            sum_wt  += r.line_val[i];
        }
    }

    if (sum_wt > 0.0f) {
        r.centroid         = sum_pos / sum_wt;
        r.error            = r.centroid - LA_CENTRE_INDEX;   /* −4.0 to +4.0 */
        r.error_mm         = r.error * LA_SENSOR_SPACING_MM; /* −40 to +40 mm */
        r.is_line_lost     = false;
        _lost_cycles       = 0;
        r.lost_duration_ms = 0;
    } else {
        r.centroid         = NAN;
        r.error            = NAN;
        r.error_mm         = NAN;
        r.is_line_lost     = true;
        _lost_cycles++;
        r.lost_duration_ms = _lost_cycles * (1000U / LA_UPDATE_RATE_HZ);
    }

    /* ── Step 8: Junction / Intersection detection ───────────────────────── */
    if (r.active_count >= LA_JUNCTION_MIN_SENSORS) {
        _junction_consec++;
        if (_junction_consec >= LA_JUNCTION_CONSEC_SAMPLES) {
            r.is_junction = true;
            /* Saturate counter to prevent overflow */
            if (_junction_consec > LA_JUNCTION_CONSEC_SAMPLES + 20)
                _junction_consec = LA_JUNCTION_CONSEC_SAMPLES;
        }
    } else {
        _junction_consec = 0;
        r.is_junction    = false;
    }

    /* ── Step 9: Store result ────────────────────────────────────────────── */
    memcpy(&_last_result, &r, sizeof(LA_Result_t));
    memcpy(result, &r, sizeof(LA_Result_t));
}

void LA_Reset(void) {
    _junction_consec = 0;
    _lost_cycles     = 0;
}

void LA_PrintDebug(const LA_Result_t *r, UART_HandleTypeDef *huart) {
    if (!r || !huart) return;

    char buf[128];
    int  n = 0;

    /* ASCII bar chart: '#' = on line, '.' = off line */
    n += snprintf(buf + n, sizeof(buf) - n, "[LA] ");
    for (int i = 0; i < LA_NUM_SENSORS; i++) {
        buf[n++] = (r->line_val[i] > LA_ACTIVE_THRESHOLD) ? '#' : '.';
    }

    if (!isnan(r->error)) {
        n += snprintf(buf + n, sizeof(buf) - n,
                      " | err=%+.2f (%+.0fmm) | act=%d%s%s\r\n",
                      (double)r->error,
                      (double)r->error_mm,
                      r->active_count,
                      r->is_junction  ? " JXN"  : "",
                      r->is_line_lost ? " LOST" : "");
    } else {
        n += snprintf(buf + n, sizeof(buf) - n,
                      " | LINE LOST (%lu ms)\r\n",
                      (unsigned long)r->lost_duration_ms);
    }

    HAL_UART_Transmit(huart, (uint8_t *)buf, (uint16_t)n, 10);
}

void LA_GetCalibration(LA_Calibration_t *cal) {
    if (cal) memcpy(cal, &_cal, sizeof(LA_Calibration_t));
}

/* ─── PD Line Following Controller ────────────────────────────────────────── */

void LF_Init(LF_Controller_t *lf, float kp, float kd, float wz_max, float dt) {
    lf->kp         = kp;
    lf->kd         = kd;
    lf->wz_max     = wz_max;
    lf->dt         = dt;
    lf->prev_error = 0.0f;
    lf->has_prev   = false;
}

float LF_ComputeOmega(LF_Controller_t *lf, float error) {
    /* Line lost — no steering output */
    if (isnan(error)) return 0.0f;

    float d_term = 0.0f;
    if (lf->has_prev) {
        /* Rate of change of error: positive = error growing (going more right) */
        d_term = (error - lf->prev_error) / lf->dt;
    }

    /* PD: positive error → turn right → positive omega (convention: right = positive) */
    float omega = lf->kp * error + lf->kd * d_term;

    /* Clamp to maximum angular velocity */
    if      (omega >  lf->wz_max) omega =  lf->wz_max;
    else if (omega < -lf->wz_max) omega = -lf->wz_max;

    lf->prev_error = error;
    lf->has_prev   = true;
    return omega;
}

void LF_Reset(LF_Controller_t *lf) {
    lf->prev_error = 0.0f;
    lf->has_prev   = false;
}
